---
- hosts: localhost
  become: false
  name: Macbook Playbook
  gather_facts: False

  vars:
    TFENV_ARCH: amd64
    Brew_packages:
      - asciidoctor
    install_homebrew_if_missing: true
    ccompiler:
      CC: gcc

  environment:
    CC: gcc

  # Pre-requisites
  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      fail:
        msg: Homebrew is missing, install from http://brew.sh
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing

    - name: Installing Homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing

  #####################################################################
  #                                                                   #
  # Tasks (install)                                                   #
  #                                                                   #
  #####################################################################
  tasks:
    - name: Ensures taps are present via homebrew
      community.general.homebrew_tap:
        name: "{{ item }}"
        state: present
      with_items:
        - hashicorp/tap
        - d12frosted/emacs-plus

    # - name: Ensures packages are present via homebrew cask
    #   community.general.homebrew_cask:
    #     name: "{{ item }}"
    #     state: present
    #     install_options: 'appdir=/Applications'
    #   with_items:
    #     - 1password
    #     - chromedriver
    #     - dbeaver-community
    #     - docker
    #     - dropbox
    #     - firefox
    #     - google-chrome
    #     - handbrake
    #     - kitty
    #     - licecap
    #     - multipass
    #     - sequel-ace
    #     - slack
    #     - spotify
    #     - sublime-text
    #     - transmit
    #     # - visual-studio-code
    #   ignore_errors: yes
    #   tags:
    #     - applications

    - name: Ensures packages are present via homebrew
      community.general.homebrew:
        name: "{{ item }}"
        path: "/Applications"
        state: present
      with_items:
        - autoconf
        - awscli
        - awk
        - fzf
        - git
        - gnupg
        - go
        - helm
        - htop
        - httpie
        - hugo
        - iperf
        - libevent
        - jq
        - jsonnet
        - k9s
        - kind
        - kubectx
        - kubernetes-cli
        - lazydocker
        - lazygit
        - libgccjit
        - mcrypt
        - neovim
        - node
        - nvm
        - openssl
        - poetry
        - pv
        - pyenv # https://faun.pub/pyenv-multi-version-python-development-on-mac-578736fb91aa
        - readline
        - sqlite3
        - sshuttle
        - stern
        - terraform
        - terragrunt
        - tmux
        - wget
        - wrk
        - xz
        - yq
        - zlib
      ignore_errors: yes
      tags:
        - packages

    - name: Ensures Emacs is installed with Homebrew
      community.general.homebrew:
        name: "{{ item }}"
        path: "/Applications"
        state: present
        install_options: 'appdir=/Applications,with-native-comp,with-xwidgets,with-no-frame-refocus,with-modern-pen-icon'
      with_items:
        - emacs-plus@29

    # # TODO: Check if this is needed
    # - name: Create symbolic link for Emacs
    #   file:
    #     src: "/opt/homebrew/opt/emacs-plus@29/Emacs.app"
    #     dest: "/Applications"
    #     state: link
    #   ignore_errors: yes

    - name: Install Asciidoctor
      # Ansible offers different modules that can do different things
      homebrew:
        name: asciidoctor
        state: present
